export const TOGGLE_CART_DROPDOWN_ICON = 'TOGGLE_CART_DROPDOWN_ICON'
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const GET_CATEGORIES_BEGIN = 'GET_CATEGORIES_BEGIN'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR'

export const GET_PRODUCT_BEGIN = 'GET_PRODUCT_BEGIN'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR'